addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.21")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"      % "2.2.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-osgi"     % "0.9.6")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.5.1")
addSbtPlugin("com.github.sbt"   % "sbt-dynver"   % "5.0.1")
