addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.17")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"      % "2.2.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-osgi"     % "0.9.6")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
