addSbtPlugin("com.github.sbt"   % "sbt-release"  % "1.1.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.13")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"      % "2.1.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-osgi"     % "0.9.6")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.4.6")
