/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xerial_snappy_BitShuffleNative */

#ifndef _Included_org_xerial_snappy_BitShuffleNative
#define _Included_org_xerial_snappy_BitShuffleNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xerial_snappy_BitShuffleNative
 * Method:    supportBitSuffle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xerial_snappy_BitShuffleNative_supportBitSuffle
  (JNIEnv *, jobject);

/*
 * Class:     org_xerial_snappy_BitShuffleNative
 * Method:    bitShuffle
 * Signature: (Ljava/lang/Object;IIILjava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_org_xerial_snappy_BitShuffleNative_bitShuffle
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     org_xerial_snappy_BitShuffleNative
 * Method:    bitUnShuffle
 * Signature: (Ljava/lang/Object;IIILjava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_org_xerial_snappy_BitShuffleNative_bitUnShuffle
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
