/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xerial_snappy_SnappyNative */

#ifndef _Included_org_xerial_snappy_SnappyNative
#define _Included_org_xerial_snappy_SnappyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xerial_snappy_SnappyNative
 * Method:    nativeLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xerial_snappy_SnappyNative_nativeLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_xerial_snappy_SnappyNative
 * Method:    rawCompress
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_xerial_snappy_SnappyNative_rawCompress
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint);

/*
 * Class:     org_xerial_snappy_SnappyNative
 * Method:    rawUncompress
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_xerial_snappy_SnappyNative_rawUncompress
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint);

/*
 * Class:     org_xerial_snappy_SnappyNative
 * Method:    maxCompressedLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_xerial_snappy_SnappyNative_maxCompressedLength
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_xerial_snappy_SnappyNative
 * Method:    getUncompressedLength
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_xerial_snappy_SnappyNative_getUncompressedLength
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
